---
jupyter: python3
---

# More on Working with Raster Data

## Intro and Objectives

It is quite common that the raster data you have in hand is too large to process, or not all the pixels are relevant to your area of interest (AoI). In both situations, you should consider cropping your raster data before performing data analysis.

In this module, we will introduce how to crop raster data into the desired area. We will use one Sentinel-2 image as the example raster data, and introduce how to crop your data to different types of AoIs.

Our objective are:

- Raster data computations
- Working with nodata values
- Clipping or cropping of raster data

## Readings and Resources

- GCwP - [Section 3.3: Spatial operations on raster data](https://py.geocompx.org/03-spatial-operations#sec-spatial-ras)
- GCwP - [Section 4.3: Geometric operations on raster data](https://py.geocompx.org/04-geometry-operations#sec-geo-ras)

## Introduce the Data

We will use the image file that we downloaded and saved from the last notebook. You can
find the T17TLH_20240401T162831_TCI_10m.tif file in TODO. 



We also use the cropped fields polygons `fields_cropped.shp`, which was generated in an exercise from [Episode 7: Vector data in python](07-vector-data-in-python.md).


### Activities

For each section of the case study, there will usually
be a compressed archive to download which contains the Jupyter notebook(s) as
well as any data (or other) files needed. In addition, there will be one or more
screencasts that walk you through the notebooks.

Start by downloading the following file and extract it in a location of your choice.

Launch Jupyter lab and open the **ou_land_use_01_rasterintro.ipynb** file. Work your
way through out. There is also a screencast to help walk you through the notebook.

- Download: [ou_land_use_01_rasterintro.zip]()

There is a single screencast that goes along with this section:

- Screencast: [Intro to raster data and land use on the OU campus]()

